[[mgr.prepend_keymap]]
on = "<Up>"
run = "arrow 1"
desc = "Move down (reversed for bottom-aligned)"

[[mgr.prepend_keymap]]
on = "<Down>"
run = "arrow -1"
desc = "Move up (reversed for bottom-aligned)"
